### ISSUE TITLE
Epic: Evaluate the performance of KS components by conducting stress testing experiments

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/kubestellar#1009]
This epic is about the on-going work to conduct experiment to stress test the all KubeStellar components:

This epic tracks all tasks needed:
- [ ] Select the target workload: MCAD appWrappers
- [ ] Select the experiment environment: KS staging environment (4 OCP clusters)
- [ ] Design stress test experiment: focus on (size, number, and rate) of appWrapper creation, deployment, removal, status, etc.
- [ ] Conduct stress test experiments

**Comment by clubanderson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GH](https://trello.com/c/WwIGmx21/3-gh)

**Comment by dumb0002** [comment]
Conducted short duration stress test:

**Experiment-1:**

- Stress test MCAD + KS stack by creating n appwrappers (AW) (where n=10, 100, 200, 500, 1000)

- Workload Generation Tool: clusterloader2 –https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/README.md

- Workload Generation Function: used clusterloader tuningSet RandomizedLoad with AverageQPS set to 10

- Sample Workload:  https://github.com/dumb0002/perf-tests/blob/mcc-exp/clusterloader2/testing/load/appwrapper-small.yaml

- Appwrapper:
   Yaml file size: 1.6KB
   It encapsulates a simple K8s job that sleeps for 20 seconds
  Job deploys one pod that requests 1 half CPU & 512MB RAM

**Measurements:** 
- CPU & Memory usage
- Key latencies for AppWrapper creation and status propagation in the MCAD + KS stack to identify any bottleneck step

**Target components:**
  - KubeStellar & KubeStellar Syncers
  - MCAD dispatcher & agents
  - KS-Plugin

**Comment by dumb0002** [comment]
This work is completed!
