### ISSUE TITLE
epic: Prometheus metrics

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2158]
There are several things that we should do about Prometheus metrics.

- [ ] expose `/metrics` from the kubestellar-controller-manager, connected to at least the metrics from the kubernetes libraries.
- [ ] expose `/metrics` from the generic transport controller, connected to at least the metrics from the kubernetes libraries.
- [ ] expose `/metrics` from the OCM Status Add-On Agent, connected to at least the metrics from the kubernetes libraries.
- [ ] add metrics on apiserver request/responses from kubestellar-controler-manager.
- [ ] add metrics on apiserver request/responses from generic transport controller.
- [ ] add mission-specific metrics (e.g., number of bound objects, WECs per Binding[Policy]) to kubestellar-controller-manager. FYI, Issue #959 had some suggestions for the legacy system.
- [ ] add mission-specific metrics (e.g., sizes of wrapped objects) to generic transport controller.
- [ ] add mission-specific metrics (e.g., sizes of wrapped objects) to the OCM Status Add-On Agent.
- [ ] Find or create documentation on metrics from the OCM pods involved.

**Comment by MikeSpreitzer** [comment]
This is not entirely unrelated to #2094

**Comment by MikeSpreitzer** [comment]
Ugh. Of course controller-runtime does it differently. See https://book.kubebuilder.io/reference/metrics.html for some clues.

**Comment by MikeSpreitzer** [comment]
Also, as always, OpenShift has its own opinion about how to get metrics scraped. https://book.kubebuilder.io/reference/metrics.html#exporting-metrics-for-prometheus talks about the provisions for that in controller-runtime. This is only an FYI, scraping is beyond the scope of this epic.

**Comment by MikeSpreitzer** [comment]
Regarding the OCM Status Add-On: although the framework (https://github.com/open-cluster-management-io/addon-framework/tree/v0.8.1) imports controller-runtime, that is only used in testing. The regular code does not use controller-runtime. Currently ks/OSA's controller and agent offer no metrics.

**Comment by MikeSpreitzer** [comment]
I ran the bash E2E test, using commit 5b6b18e26, and scraped the metrics. I have attached the results.

[kubestellar-controller-manager.metrics.txt](https://github.com/user-attachments/files/15570518/kubestellar-controller-manager.metrics.txt)

[ocm-status-addon-agent.metrics.txt](https://github.com/user-attachments/files/15570519/ocm-status-addon-agent.metrics.txt)

[ocm-status-addon-controller.metrics.txt](https://github.com/user-attachments/files/15570522/ocm-status-addon-controller.metrics.txt)

[transport-controller.metrics.txt](https://github.com/user-attachments/files/15570523/transport-controller.metrics.txt)

The processes based on controller-runtime have an impoverished set of rest_client metrics.

The OCM Status Add-On Agent also lacks _any_ workqueue metrics.

**Comment by MikeSpreitzer** [comment]
I think it is not going to be easy to change our controller-runtime based controllers to produce the normal client-go metrics that they currently do not. Witness the complaint and lack of response to https://kubernetes.slack.com/archives/C02MRBMN00Z/p1717604240073959 . Witness the exclusive registration of just one client-go metric at https://github.com/kubernetes-sigs/controller-runtime/blob/v0.18.3/pkg/metrics/client_go_adapter.go#L51-L54 , implying that controller-runtime has other ways of collecting the same or equivalent metrics, the absence of which I suppose is because our controllers are not using the relevant part(s) of controller-runtime.

To be clear, I am not saying that we can not _add_ our own metrics; https://book.kubebuilder.io/reference/metrics.html#publishing-additional-metrics shows how to do that.

Since we plan to shift away from using controller-runtime, I am disinclined to pursue the missing client-go metrics unless and until I hear that some of those are specifically desired.

**Comment by MikeSpreitzer** [comment]
Following are the ports where /metrics is available.

- HTTP port 8080 on the kubestellar controller-manager
- HTTP port 8090 on the transport controller
- HTTP port 9280 on the OCM Status Add-On Controller
- HTTP port 8080 on the OCM Status Add-On Agent

**Comment by MikeSpreitzer** [comment]
I just check off the following items, but they were accomplished many months ago.
- add metrics on apiserver request/responses from kubestellar-controler-manager
- add metrics on apiserver request/responses from generic transport controller

**Comment by clubanderson** [comment]
Closing this epic as implemented. Prometheus metrics are now fully available:
- `pkg/metrics/` directory contains the implementation (client.go, sampler.go, wrap_client.go, etc.)
- All metrics endpoints are documented in `docs/content/direct/observability.md`
- Metrics exposed at: kubestellar-controller-manager:8443, ks-transport-controller:8090, status-addon-controller:9280, status-addon-agent:8080
- Example Grafana dashboards available in `monitoring/grafana/`
