### ISSUE TITLE
epic: give users control over client-side self-restraint

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2159]
The Kubernetes client libraries exercise self-restraint in the rate (well, actually it is more general) at which they send requests to the apiserver(s). The general form is https://github.com/kubernetes/client-go/blob/v0.28.2/rest/config.go#L123 . Commonly the special case of https://github.com/kubernetes/client-go/blob/v0.28.2/rest/config.go#L114-L120 is used. All of our clients should expose these parameters for every kube client config.

- [x] kubestellar-controller-manager
- [x] generic transport controller
- [x] OCM Status Addo-On Agent. This intersects a larger design question:
- [x] Design how the OCM Status Add-On Controller controls the agent command line (https://github.com/kubestellar/ocm-status-addon/issues/57)
- [x] Implement the controller's control over the agent command line and plumb through ks/OSA Helm chart (https://github.com/kubestellar/ocm-status-addon/pull/67)
- [ ] kubestellar controller-manager Helm chart
- [ ] OCM Status Add-On Helm chart, wrt controller
- [x] OCM Status Add-On Helm chart, wrt agent
- [x] OCM transport controller Helm chart
- [ ] core chart has parameters for kubestellar controller-manager
- [ ] core chart has parameters for OCM transport controller
- [ ] core chart has parameters for OCM Status Add-On controller
- [x] core chart has parameters for OCM Status Add-On agent (#2184)

**Comment by clubanderson** [comment]
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

**Comment by clubanderson** [comment]
Rotten issues close after 30d of inactivity.
Reopen the issue with `/reopen`.
Mark the issue as fresh with `/remove-lifecycle rotten`.

/close
