### ISSUE TITLE
EPIC:  Use KubeStellar without KCP core  Milestone1

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#524]
This epic tracks all tasks needed for milestone1 of decoupling KCP and KS.

# Milestone1 goals
- Demonstrate fully functional KS while the KCP server is not running, 
- KS code doesn't use the KCP k8s fork (directly or indirectly).  - TBD if optional or mandatory
  - Stop using KCP's code generators, 
  - Don't use KCP runtime 

## Open issues
- Do we want to continue supporting KCP export/bind after the decoupling (using some abstraction that will allow supporting both kube-bind & KCP bind)
  - Only impact the bind/export performance. We can have a Space provided by a KCP provider while using kube-bind
  - Adding a complexity level + additional (significant?) work 

## Main areas:
- Use alternatives to KCP workspaces 
- Use alternatives to KCP's implementation of APIExport/APIBind, 
  - Use alternatives for KCP's APIExport Views 
- Be able to denature base k8s resources for providers that don't denature resources (e.g., for KIND space provider)
- Don't use code based on the k8s fork of KCP (e.g., generated go-client code)

#### Additional tasks
- Update KS architecture documentation to include the Space framework, new bind functions, etc..
- Update the KS user documentation 
- Update KS setup and configuration
- Update KS testing

# List of Issues & PRs for milestone1
## Stop using KCP's workspaces
- [x] #849 
- [x]  Merge the space framework and multi-space client library into KS
- [x] #931
- [x] #977
  - [x] #989
  - [x] place-holder:  Convert the space-framework into a go module
- [x] #1012
  - [x] #1013 
- [x] #976 
  - [x] #1015 
- [x] #852 
  - [ ] #1218 
- [x] #853 
  - [ ] #904 
  - [ ] #923 
#### Delivery description & Impact on KubeStellar
The items listed above don't add new functionality to KS. KS will still need to use KCP server in order to support bind & export. The main reasons to integrate the above changes are:
1. Avoid maintaining a side branch till all the needed code for milestone1 is ready (which can take couple of months)
2. Minimize the potential impact on KS by gradually integrating the needed components (instead of a single huge transition phase) 

## Use kube-bind 
- [x] #525 
  - [x] https://github.com/kube-bind/kube-bind/pull/165
  - [x] https://github.com/kube-bind/kube-bind/pull/166
  - [x] https://github.com/kube-bind/kube-bind/pull/174
  - [x] https://github.com/kube-bind/kube-bind/pull/175
- [x] #870 

#### Delivery description & Impact on KubeStellar
In case we don't plan to support KCP export/bind these changes are irreversible. As stated before the only main impact is the performance difference as KCP export/bind is much more efficient. No impact is expected on the KS functionality or user experience.

## Testing 
- [ ] Add KS e2e testing with different Space providers

# Optional items  scheduled to follow-on milestones
### Denaturing of k8s resources 
For milestone1 we can use KubeFlex for workload that uses k8s objects (Pods, deployments, etc..) and use k8s or KIND providers for workloads that use special CRDs (e.g., AppWrapper) 
On going work on denaturing is in: #353

### Stop using the KCP code generators
Switch to use the k8s vanilla code generators instead of using the KCP's ones which inject the cluster support abstraction based on the k8s fork

**Comment by clubanderson** [comment]
pushing to next sprint so that the remaining list of things 'todo' can be added

**Comment by MikeSpreitzer** [comment]
In the "goals" section, under "KS code doesn't use the KCP k8s fork (directly or indirectly).", I would not put "Don't use KCP runtime" (I think that is covered by "Demonstrate fully functional KS while the KCP server is not running"?).  I would put "do not have any static (i.e., build-time) dependency on kcp", and split that into "direct" and "indirect".  I think the goal should be to not have a direct static dependency; I think an indirect dependency is OK in the context of pictures like I have been drawing that make it clear that this is about preserving a run-time _option_.

**Comment by clubanderson** [comment]
@ezrasilvera please update this epic to reflect current status

**Comment by clubanderson** [comment]
@ezrasilvera can you please update/close...

**Comment by ezrasilvera** [comment]
This moved to be tracked by #1266
